######
## Script name: validate_assignment.py
## Date: July 2023
## Author: Matteo Carrara (NEXUS Personalized Health Technologies)
##
## Description: Part of the Revseq pipeline. Loads the metadata table from Viollier and
##        adds to the assignment table which viruses are positive according to the
##        clinical tests for comparison with the in-silico assignment
######

import pandas as pd
import argparse, os, glob, math, sys

# Script
if __name__ == '__main__':
	# Parse input args
    parser = argparse.ArgumentParser(description='fetch the primers positions on the reference', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--metadata_dir', required=True, type=str, help='directory containing the metadata files')
    parser.add_argument('--anonymization_table', required=True, type=str, help='table containing the anonymization matching')
    parser.add_argument('--output', required=True, type=str, help='Path and name of the output table')
    parser.add_argument('--ethid', required=True, type=str, help='Anonymized name of the sample to validate')
    parser.add_argument('--match_table', required=True, type=str, help='TSV matching the panel code with the common virus name used in the pipeline')
    parser.add_argument('--count_table', required=True, type=str, help='Major count table as generated by assign_virus.py')

    anontable = pd.read_table(args.anonymization_table)
    match_table = pd.read_csv(args.match_table,sep="\t", header=None)
    count_table = pd.read_csv(args.count_table)
    metadata_files = os.listdir(metadata_dir)
    all_files = glob.glob(os.path.join(args.metadata_dir, "*.csv"))
    metadata = pd.concat((pd.read_csv(f, sep=";") for f in all_files), ignore_index=True)
    sample_name = anontable.loc[anontable['ethid'] == args.ethid]['sample_name'].astype(int)
    sample_name = int(sample_name.iloc[0])
    metadata = metadata.loc[metadata['Sample number'] == sample_name]
    if len(metadata.index) == 0:
        sys.exit("ERROR: cannot find the sample name associated to ethid " + ethid + " in the metadata table!")
    
    metadata = metadata.to_dict(orient='list')
    positive = []
    for key,value in metadata.items():
        value = value[0]
        # Current metadata has an empty cell, nan or "deleted" for missing values; 0 or -1 for negatives; 4 or a positive integer >4 for positives
        if (type(value) == str) or (math.isnan(value) or (value <= 0) or (key == 'Sample number')):
            continue
        elif value > 0:
            positive.append(key.split(" ")[0])
        else:
            sys.exit("ERROR: Unexpected value in the metadata table!")

    for virus in positive:
            common_name = match_table[match_table[0] == virus][1].to_string(index=False)

    if len(count_table[count_table.index == common_name]) == 0:
        sys.exit("ERROR: common virus name ", common_name, " not found in the count table!")
    count_table['panel_positive'] = ""
    count_table['panel_positive'] = count_table[['outlier']].apply(lambda x: "positive" if x['outlier']=="*" else "", axis=1)
    count_table.to_csv(args.output)
