version: "3"
volumes:
  pg_data:
  web_root:
services:
  ui:
    build:
      context: ui
    volumes:
      - ./ui/app:/app
      - "web_root:/app/dist:z"
    hostname: ui
    restart: "no"
    env_file: .env

  api:
    build:
      context: api
    hostname: api
    restart: unless-stopped
    entrypoint: sh -c '/app/entrypoint.sh'
    volumes:
      - ./api/app:/app
      - ./api/backups:/vol/backups
      - ./api/static:/vol/web/static:z
      - ./api/media:/vol/web/media:z
      - ./data:/data
      - ./README.md:/app/README.md
      - ./.git:/app/docs/.git
    env_file: .env
    environment:
      - GIT_VERSION=${GIT_VERSION}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_LASTCOMMITDATE=${GIT_LASTCOMMITDATE}
    depends_on:
      - db
  ena:
    image: ethnexus/ena-upload-ms:1.2.8
    hostname: ena
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${ENA_POSTGRES_DB}
      - POSTGRES_USER=${ENA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ENA_POSTGRES_PASSWORD}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
      - DJANGO_CORS_ALLOWED_ORIGINS=${DJANGO_CORS_ALLOWED_ORIGINS}
      - ENA_USERNAME=${ENA_USERNAME}
      - ENA_PASSWORD=${ENA_PASSWORD}
      - ENA_USE_DEV_ENDPOINT=${ENA_USE_DEV_ENDPOINT}
      - ENA_UPLOAD_FREQ_SECS=${ENA_UPLOAD_FREQ_SECS}
      - ENA_TOKEN=${ENA_TOKEN}
      - ENA_PROXY_PREFIX=${ENA_PROXY_PREFIX}
    volumes:
      - ./ena/templates:/templates
      - ./data:/data
    depends_on:
      - db
  db:
    image: postgres:13.4-alpine
    hostname: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init_ena_db.sh:/docker-entrypoint-initdb.d/init_ena_db.sh
