checklist: ERC000033
center_name: ETH Zurich
laboratory: Computational Evolution group

# Overall ENA research project
study:
  alias: revseq_study
  title: Respiratory Virus Sequencing
  study_type: RNASeq
  study_abstract: Respiratory Virus Sequencing
  pubmed_id:

#
sample:
  alias: revseq_sample_{}
  title: ReVSeq Sample
  taxon_id: 269049 # (mapping from substrain)
  sample_description: ReVSeq Sample Description
  # dynamic
  host subject id: xx
  collection date: 2023-11-10
  geographic location (region and locality): CANTON
  # static
  geographic location (country and/or sea): Switzerland
  host common name: Human
  host health state: "missing: human-identifiable"
  host sex: "missing: human-identifiable"
  host scientific name: Homo Sapiens
  collector name: "Viollier AG"
  collecting institution: Viollier AG
  isolate: "Respiratory swabs"
  

#
experiment:
  alias: revseq_experiment_{}
  title: ReVSeq Experiment
  study_alias: revseq_study
  sample_alias: revseq_sample_{}
  design_description: "None"
  library_name: "None"
  library_strategy: RNA-Seq
  library_source: METAGENOMIC
  library_selection: cDNA
  library_layout: "paired"
  insert_size: 250
  library_construction_protocol: "None"
  platform: illumina
  instrument_model: Illumina MiSeq

#
run:
  alias: revseq_run_{}
  experiment_alias: revseq_experiment_{}

#
analysis:
  name: analysis_{}
  assembly_type: clone
  coverage: 3.7
  program: TODO
  platform: TODO
