inputOutput:
  # full path to directory with input files
  input_fastqs: "/Users/mcarrara/repos/revseq/raw_data"
  sample_map: "config/sample_map.tsv"

resources:
  primer_file: "/Users/mcarrara/repos/revseq/RespiratoryVirus.20200409.bed"
  host_ref: "/Users/mcarrara/repos/revseq/RespiratoryVirus_hg38.20200409.fa"
  reference: "/Users/mcarrara/repos/revseq/RespiratoryVirus.20200409.fa"

tools:
  trim_galore:
    min_length: 80
    min_length_single: 90
  consensus:
    min_freq: 0.05
    min_cov: 100
  dehuman:
    conda: "../envs/dehuman.yaml"
    keep_host: 0
    checksum: md5
    threads: 1
  bwa_align:
    threads: 1
  fetch_primers:
    primerout: "results/fetch_primers/primers.tsv"

  