inputOutput:
  # full path to directory with input files
  input_fastqs: "/Users/mcarrara/repos/revseq/anondata"
  sample_map: "config/sample_map.tsv"

resources:
  primer_file: "/Users/mcarrara/repos/revseq/RespiratoryVirus.20200409.bed"
  host_ref: "/Users/mcarrara/repos/revseq/RespiratoryVirus_hg38.20200409.fa"
  reference: "/Users/mcarrara/repos/revseq/RespiratoryVirus.20200409.fa"
  reference_dir: "/Users/mcarrara/repos/revseq"

threads: 4

tools:
  trim_galore:
    min_length: 20
    min_length_single: 30
  consensus:
    min_freq: 0.05
    min_cov: 100
  #dehuman:
  #  conda: "../envs/dehuman.yaml"
  #  keep_host: 0
  #  checksum: md5

  