import_columns:
  deep_well_location: DeepWellLocation
  sample_number: Sample number
  pseudonymized_id: ethid
  order_date: Order date
  ent_date: ent date
  treatment_type: treatment_type
  prescriber_canton: Prescriber canton
  name: name
  outlier: outlier
  aligned: aligned_reads
  length: reference_length
  rpkm: rpkm
  rpkm_proportions: rpkm_proportions
  coverage_threshold: coverage_threshold
  coverage: coverage
  coverage_status: coverage_status
  readnum_status: readnum_status
  readnum_threshold: readnum_threshold
  percentile_threshold: percentile_threshold
  tax_id: tax_id
  scientific_name: scientific_name
  DP: DP
  consensus_number_n: consensus_number_n
  consensus_fraction_n: consensus_fraction_n

metadata_table_fields:
  order_date: "Order date"
  ent_date: "ent date"
  treatment_type: "treatment_type"
  prescriber: "Prescriber canton"


