import_columns:
  deep_well_location: DeepWellLocation
  sample_number: Sample number
  pseudoanonymized_id: pseudoanonymized_id
  order_date: Order date
  ent_date: ent date
  treatment_type: treatment_type
  prescriber_canton: Prescriber canton
  name: name
  outlier: outlier
  aligned: aligned
  length: length
  rpkm: rpkm
  rpkm_proportions: rpkm_proportions
  normcounts: normcounts
