import_columns:
  deep_well_location: DeepWellLocation
  sample_number: Sample number
  pseudonymized_id: ethid
  order_date: Order date
  ent_date: ent date
  treatment_type: treatment_type
  prescriber_canton: Prescriber canton
  name: name
  outlier: outlier
  aligned: aligned_reads
  length: reference_length
  rpkm: rpkm
  rpkm_proportions: rpkm_proportions
  DP_threshold: DP_threshold
  DP: DP
  DP_status: DP_status
  readnum_status: readnum_status
  readnum_threshold: readnum_threshold
  percentile_threshold: percentile_threshold

