#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$ENA_POSTGRES_USER";
	ALTER USER "$ENA_POSTGRES_USER" PASSWORD '$ENA_POSTGRES_PASSWORD';
	CREATE DATABASE "$ENA_POSTGRES_DB" OWNER "$ENA_POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "$ENA_POSTGRES_DB" TO "$ENA_POSTGRES_USER";
	CREATE DATABASE "${ENA_POSTGRES_DB}_dev" OWNER "$ENA_POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "${ENA_POSTGRES_DB}_dev" TO "$ENA_POSTGRES_USER";
EOSQL
