# Generated by Django 4.2.4 on 2023-08-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.TextField(unique=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('panel_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.TextField(unique=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Substrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strain')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aligned', models.IntegerField()),
                ('length', models.IntegerField()),
                ('rpkm', models.FloatField()),
                ('rpkm_proportions', models.FloatField()),
                ('normcounts', models.FloatField()),
                ('outlier', models.BooleanField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sample')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strain')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.well'),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strain')),
            ],
        ),
    ]
