# Generated by Django 4.2.4 on 2024-01-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postfix', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.TextField(unique=True)),
                ('pseudonymized_id', models.TextField(null=True, unique=True)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('analysis_job_id', models.IntegerField(blank=True, null=True)),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Substrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('taxon_id', models.IntegerField(null=True)),
                ('scientific_name', models.TextField(null=True)),
                ('strain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.strain')),
            ],
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aligned', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('rpkm', models.FloatField(null=True)),
                ('rpkm_proportions', models.FloatField(null=True)),
                ('normcounts', models.FloatField(null=True)),
                ('outlier', models.BooleanField(null=True)),
                ('DP_threshold', models.FloatField(blank=True, null=True)),
                ('DP', models.FloatField(blank=True, null=True)),
                ('DP_status', models.CharField(blank=True, max_length=20, null=True)),
                ('readnum_status', models.TextField(blank=True, null=True)),
                ('readnum_threshold', models.FloatField(blank=True, null=True)),
                ('percentile_threshold', models.TextField(blank=True, null=True)),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplecounts', to='core.plate')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplecounts', to='core.sample')),
                ('substrain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplecounts', to='core.substrain')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.well'),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('strain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.strain')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriber', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('ent_date', models.DateField()),
                ('treatment_type', models.CharField(max_length=20, null=True)),
                ('data', models.JSONField(default=list, null=True)),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.plate')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.sample')),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.well')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('checksum', models.TextField(unique=True)),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sample')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filetype')),
            ],
        ),
    ]
