# Generated by Django 4.2.4 on 2024-01-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplecount',
            old_name='DP',
            new_name='coverage',
        ),
        migrations.RenameField(
            model_name='samplecount',
            old_name='DP_status',
            new_name='coverage_status',
        ),
        migrations.RenameField(
            model_name='samplecount',
            old_name='DP_threshold',
            new_name='coverage_threshold',
        ),
        migrations.AddField(
            model_name='samplecount',
            name='DP20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='scientific_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='tax_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
