# Generated by Django 4.2.4 on 2023-08-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecount',
            name='strain',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='panel_name',
        ),
        migrations.AddField(
            model_name='samplecount',
            name='substrain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.substrain'),
        ),
        migrations.AlterField(
            model_name='substrain',
            name='strain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.strain'),
        ),
    ]
