# Generated by Django 4.2.4 on 2023-08-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_samplecount_strain_remove_strain_panel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='strain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.strain'),
        ),
    ]
