# Generated by Django 4.2.4 on 2024-01-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_dp_samplecount_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='checksum',
            field=models.TextField(),
        ),
    ]
