# Generated by Django 4.2.4 on 2023-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_panel_strain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecount',
            name='aligned',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='normcounts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='outlier',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='rpkm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='rpkm_proportions',
            field=models.FloatField(null=True),
        ),
    ]
