# Generated by Django 4.2.4 on 2024-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_file_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='not_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
