# Generated by Django 4.2.4 on 2023-08-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_samplecount_aligned_alter_samplecount_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecount',
            name='sample',
        ),
        migrations.AddField(
            model_name='samplecount',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate'),
        ),
    ]
