# Generated by Django 4.2.4 on 2023-08-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_samplecount_sample_samplecount_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='well_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='pseudoanonymized_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='well',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriber', models.CharField(max_length=20)),
                ('sample_number', models.IntegerField()),
                ('order_data', models.DateField()),
                ('ent_data', models.DateField()),
                ('treatment_type', models.CharField(max_length=20, null=True)),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
                ('well', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.well')),
            ],
        ),
    ]
