# Generated by Django 4.2.4 on 2023-08-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_well_well_id_sample_pseudoanonymized_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='sample_id',
            new_name='sample_number',
        ),
    ]
