# Generated by Django 4.2.4 on 2024-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_samplecount_not_valid_sample_not_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='not_valid',
        ),
        migrations.AddField(
            model_name='sample',
            name='valid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
