# Generated by Django 4.2.4 on 2024-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sample_not_valid_sample_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='DP1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='DP2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
