# Generated by Django 4.2.4 on 2023-08-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_sample_id_sample_sample_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='sample_number',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='plate',
        ),
        migrations.AddField(
            model_name='metadata',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sample'),
        ),
    ]
