# Generated by Django 4.2.4 on 2023-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_metadata_sample_number_remove_sample_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='data',
            field=models.JSONField(default=list, null=True),
        ),
    ]
