# Generated by Django 4.2.4 on 2024-04-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_samplecount_dp1_samplecount_dp2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecount',
            name='DP1',
        ),
        migrations.RemoveField(
            model_name='samplecount',
            name='DP2',
        ),
        migrations.RemoveField(
            model_name='samplecount',
            name='DP20',
        ),
        migrations.AddField(
            model_name='samplecount',
            name='DP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='consensus_fraction_n',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='consensus_number_n',
            field=models.TextField(blank=True, null=True),
        ),
    ]
