# Generated by Django 4.2.4 on 2023-08-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_metadata_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='ent_data',
            new_name='ent_date',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
