# Generated by Django 4.2.4 on 2023-08-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_ent_data_metadata_ent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sample'),
        ),
    ]
