# Generated by Django 4.2.4 on 2024-04-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sample_control_sample_control_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.well'),
        ),
    ]
