# Generated by Django 4.2.4 on 2023-08-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_samplecount_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate'),
        ),
    ]
