# Generated by Django 4.2.4 on 2023-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sample_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='qc_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='qc_threshold',
            field=models.FloatField(null=True),
        ),
    ]
