# Generated by Django 4.2.4 on 2024-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sample_sample_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='consensus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='consensus_cds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='consensus_fraction_n_cds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='consensus_number_n_cds',
            field=models.TextField(blank=True, null=True),
        ),
    ]
