# Generated by Django 4.2.4 on 2023-08-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_samplecount_coverage_samplecount_qc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecount',
            name='coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='qc_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='qc_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
