# Generated by Django 4.2.4 on 2024-07-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_samplecount_consensus_samplecount_consensus_cds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='ent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='prescriber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='treatment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
