# Generated by Django 4.2.4 on 2023-08-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_samplecount_coverage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplecount',
            old_name='qc_threshold',
            new_name='coverage_threshold',
        ),
    ]
