# Generated by Django 4.2.4 on 2024-07-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cdspositions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecount',
            name='consensus_fraction_n_cds',
        ),
        migrations.RemoveField(
            model_name='samplecount',
            name='consensus_number_n_cds',
        ),
    ]
