# Generated by Django 4.2.4 on 2023-09-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_qc_threshold_samplecount_coverage_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postfix', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('checksum', models.TextField(unique=True)),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sample')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filetypes')),
            ],
        ),
    ]
