# Generated by Django 4.2.4 on 2023-09-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_filetypes_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileTypes',
            new_name='FileType',
        ),
    ]
