# Generated by Django 4.2.4 on 2023-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_filetypes_filetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplecount',
            old_name='coverage',
            new_name='DP',
        ),
        migrations.RenameField(
            model_name='samplecount',
            old_name='qc_status',
            new_name='DP_status',
        ),
        migrations.RenameField(
            model_name='samplecount',
            old_name='coverage_threshold',
            new_name='DP_threshold',
        ),
        migrations.AddField(
            model_name='samplecount',
            name='percentile_threshold',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='readnum_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecount',
            name='readnum_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
