# Generated by Django 4.2.4 on 2024-07-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cdspositions_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdspositions',
            name='sample',
        ),
    ]
