# Generated by Django 4.2.4 on 2024-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_coverage_samplecount_dp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrain',
            name='scientific_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='substrain',
            name='taxon_id',
            field=models.IntegerField(null=True),
        ),
    ]
