# Generated by Django 4.2.4 on 2024-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cdspositions_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='mean_coverage_non_N_positions',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
