# Generated by Django 4.2.4 on 2024-01-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_substrain_scientific_name_substrain_taxon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecount',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
