# Generated by Django 4.2.4 on 2024-07-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_samplecount_mean_coverage_non_n_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDSCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDS_name', models.TextField()),
                ('number_n', models.TextField()),
                ('fraction_n', models.FloatField()),
                ('mean_cov_non_n_positions', models.FloatField()),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdscounts', to='core.sample')),
                ('substrain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdscounts', to='core.substrain')),
            ],
        ),
    ]
