# Generated by Django 4.2.4 on 2024-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cdscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecount',
            name='mean_coverage_non_N_positions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
