# Generated by Django 4.2.4 on 2024-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_samplecount_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplecount',
            name='job_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
