# Generated by Django 4.2.4 on 2024-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_samplecount_mean_coverage_non_n_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='mode',
            field=models.CharField(default='metagenomics', max_length=100),
        ),
    ]
