# Generated by Django 4.2.4 on 2024-01-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_samplecount_job_id_sample_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.plate'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.sample'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.well'),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplecounts', to='core.plate'),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplecounts', to='core.sample'),
        ),
        migrations.AlterField(
            model_name='samplecount',
            name='substrain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplecounts', to='core.substrain'),
        ),
    ]
