# Generated by Django 4.2.4 on 2024-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sample_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='upload_to_ena',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
