# Generated by Django 4.2.4 on 2024-01-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_metadata_plate_alter_metadata_sample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='analysis_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
