# Generated by Django 4.2.4 on 2024-01-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sample_analysis_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='pseudonymized_id',
            new_name='pseudonymized_id',
        ),
    ]
