# Generated by Django 4.2.4 on 2025-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sample_upload_to_ena'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrain',
            name='serotype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
