# Generated by Django 4.2.4 on 2025-09-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_substrain_serotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='major_strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_strain', to='core.strain'),
        ),
        migrations.AddField(
            model_name='sample',
            name='secondary_strains',
            field=models.ManyToManyField(blank=True, related_name='secondary_strains', to='core.strain'),
        ),
    ]
