# Generated by Django 4.2.4 on 2025-09-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sample_major_strain_sample_secondary_strains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='major_strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_strain', to='core.substrain'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='secondary_strains',
            field=models.ManyToManyField(blank=True, related_name='secondary_strains', to='core.substrain'),
        ),
    ]
