# Generated by Django 4.2.4 on 2025-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_sample_major_strain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='test_analysis_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
