# Generated by Django 4.2.4 on 2025-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sample_test_analysis_job_id_sample_test_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='coinfections_major_analysis_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='coinfections_minor_analysis_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_coinfections_major_analysis_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='test_coinfections_minor_analysis_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
