#!/bin/bash
#### add checks and checkpoints to avoid to upload incomplete stuff

echo "$(date) Starting the analysis loop"

# Infinite loop running once every X hours
while [[ -n "1" ]]; do
	. /data/revseq/revseq.conf
	. ${scriptdir}/revseq syncviollier
	. ${scriptdir}/revseq pseudoanonymize_samples

	for plate in $(ls -d ${anonymizeddir}/*); do
		plate=${plate##*/}
		if [ ! -f ${anonymizeddir}/${plate}/complete.txt ]; then
			echo "$(date) Found new pseudonymized plate to analyze: ${plate}"
			echo "$(date) Pipeline..."
			${scriptdir}/revseq runpipeline ${plate} #&& \
				#echo "uploading results to Viollier..." && \
				#${scriptdir}/revseq uploadviollier ${plate}
		fi
	done
	echo "$(date) Loop ended. Sleeping for ${loop_interval_hours} hours\n\n"
	sleep ${loop_interval_hours}h
done
